codecov:
  bot: "codecov-io"
  ci:
    - "travis.org"
    - "appveyor.org"
  strict_yaml_branch: master
  notify:
    require_ci_to_pass: true
ignore:
  - "build/**/*"
  - "ci/**/*"
  - "sandbox/**/*"
  - "scripts/**/*"
coverage:
  precision: 2
  range: 70...90
  round: down
  status:
    changes: off
    patch: off
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false